/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GiftsMangaRouteImport } from './routes/gifts-manga'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AnimeMangaRouteImport } from './routes/anime-manga'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsMangaRoute = GiftsMangaRouteImport.update({
  id: '/gifts-manga',
  path: '/gifts-manga',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeMangaRoute = AnimeMangaRouteImport.update({
  id: '/anime-manga',
  path: '/anime-manga',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime-manga': typeof AnimeMangaRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/gifts-manga': typeof GiftsMangaRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime-manga': typeof AnimeMangaRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/gifts-manga': typeof GiftsMangaRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime-manga': typeof AnimeMangaRoute
  '/arena': typeof ArenaRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/gifts-manga': typeof GiftsMangaRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/u/$userId': typeof UUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime-manga'
    | '/arena'
    | '/auth'
    | '/chat'
    | '/gifts-manga'
    | '/privacy'
    | '/profile'
    | '/rewards'
    | '/chat/$conversationId'
    | '/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime-manga'
    | '/arena'
    | '/auth'
    | '/chat'
    | '/gifts-manga'
    | '/privacy'
    | '/profile'
    | '/rewards'
    | '/chat/$conversationId'
    | '/u/$userId'
  id:
    | '__root__'
    | '/'
    | '/anime-manga'
    | '/arena'
    | '/auth'
    | '/chat'
    | '/gifts-manga'
    | '/privacy'
    | '/profile'
    | '/rewards'
    | '/chat/$conversationId'
    | '/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeMangaRoute: typeof AnimeMangaRoute
  ArenaRoute: typeof ArenaRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  GiftsMangaRoute: typeof GiftsMangaRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  UUserIdRoute: typeof UUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts-manga': {
      id: '/gifts-manga'
      path: '/gifts-manga'
      fullPath: '/gifts-manga'
      preLoaderRoute: typeof GiftsMangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime-manga': {
      id: '/anime-manga'
      path: '/anime-manga'
      fullPath: '/anime-manga'
      preLoaderRoute: typeof AnimeMangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeMangaRoute: AnimeMangaRoute,
  ArenaRoute: ArenaRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  GiftsMangaRoute: GiftsMangaRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  UUserIdRoute: UUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
